modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "healthindicator"
displayName = "HealthIndicator"
version = "${version}"

logoFile = "assets/healthindicator/icon.png"
authors = "uku"
description = "shows you a warning when your health goes under a certain amount"

[[dependencies.healthindicator]]
modId = "minecraft"
type = "required"
versionRange = "[26.2,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.healthindicator]]
modId = "neoforge"
type = "required"
versionRange = "[26.2.0.0-beta,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.healthindicator]]
modId = "ukulib"
type = "required"
versionRange = "[2.1.0,3)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "healthindicator.mixins.json"